name: CI Pipeline

on:
  push:
    branches:
      - branch  # Make sure 'branch' is the name of your branch
      -main
  pull_request:
    branches:
      - main  
      -branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check directory structure (frontend)
        run: |
          echo "Listing contents of the frontend directory"
          ls -al frontend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies (frontend)
        run: |
          cd frontend
          npm install --unsafe-perm=true --verbose  # Use unsafe-perm to avoid permission issues
          npm ls  # List installed dependencies for debugging

      - name: Run tests (frontend)
        run: |
          cd frontend
          npm test --verbose  # Run tests with verbose logging

      - name: Install dependencies (backend)
        run: |
          cd backend
          npm install --unsafe-perm=true --verbose  # Same for backend if necessary
          npm ls  # List installed dependencies for debugging

      - name: Run tests (backend)
        run: |
          if [ -f backend/package.json ]; then
            cd backend
            npm test --verbose
          else
            echo "No backend tests available, skipping backend test step."
          fi

  docker-build-and-deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t your-docker-username/frontend:latest .

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t your-docker-username/backend:latest .

      - name: Push Docker images
        run: |
          docker push your-docker-username/frontend:latest
          docker push your-docker-username/backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build-and-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Production (example step)
        run: |
          echo "Deploying your app"
          # Add your deployment commands here
